[package]
name = "abook"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A book manager system"
authors = ["axum.rs <team@axum.rs>"]
repository = "https://github.com/axumrs/axum-rs"
homepage = "https://axum.rs"

[dependencies]
